-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 17:56:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Research DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Research DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Research DB` DEFAULT CHARACTER SET utf8 ;
USE `Research DB` ;

-- -----------------------------------------------------
-- Table `Research DB`.`Researcher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Researcher` (
  `RID` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Fav_field` VARCHAR(45) NULL,
  PRIMARY KEY (`RID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Research Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Research Activity` (
  `ACT-ID` INT NOT NULL,
  `No_of_Pages` VARCHAR(45) NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `INTL?` TINYINT NULL COMMENT '0 for domsetic and 1 for intl',
  `Date_Recieved` INT NULL,
  `Date_of_Admission` INT NULL,
  `TYPE` VARCHAR(45) NULL COMMENT 'Generalization \n',
  `TYPE_DATE` DATE NULL,
  `TYPE_PLACE` VARCHAR(45) NULL,
  `Correspondent` INT NOT NULL,
  PRIMARY KEY (`ACT-ID`),
  INDEX `Correspondent_idx` (`Correspondent` ASC) VISIBLE,
  UNIQUE INDEX `Correspondent_UNIQUE` (`Correspondent` ASC) VISIBLE,
  CONSTRAINT `Correspondent`
    FOREIGN KEY (`Correspondent`)
    REFERENCES `Research DB`.`Researcher` (`RID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Institute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Institute` (
  `InstID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `BoolRC` TINYINT NULL,
  `BoolEXE` TINYINT NULL,
  `boolGOV?` TINYINT NULL,
  `BoolUNI` TINYINT NULL,
  PRIMARY KEY (`InstID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Funding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Funding` (
  `InstID` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  `Loan_value` INT NULL,
  `Donation_value` INT NULL,
  PRIMARY KEY (`ACT-ID`, `InstID`),
  INDEX `RID_idx` (`InstID` ASC) VISIBLE,
  CONSTRAINT `InstID`
    FOREIGN KEY (`InstID`)
    REFERENCES `Research DB`.`Institute` (`InstID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ra key`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Staff` (
  `Staff_id` INT NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Bool-RA` TINYINT NULL,
  `Bool-INS` TINYINT NULL,
  `Type` VARCHAR(45) NULL COMMENT 'domain is :\nexe\nrev\nman',
  `RA_or_inst_num` INT NOT NULL,
  PRIMARY KEY (`Staff_id`),
  INDEX `isnt_idx` (`RA_or_inst_num` ASC) VISIBLE,
  CONSTRAINT `ra`
    FOREIGN KEY (`RA_or_inst_num`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `isnt`
    FOREIGN KEY (`RA_or_inst_num`)
    REFERENCES `Research DB`.`Institute` (`InstID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`EXE_Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`EXE_Office` (
  `O_num` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Place` VARCHAR(45) NULL,
  PRIMARY KEY (`O_num`),
  INDEX `RID_idx` (`ACT-ID` ASC) VISIBLE,
  CONSTRAINT `ACT_id`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`edRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`edRecord` (
  `RECid` INT NOT NULL,
  `RID` INT NOT NULL,
  `Inst_id` INT NULL,
  PRIMARY KEY (`RECid`, `RID`),
  INDEX `rid_idx` (`RID` ASC) VISIBLE,
  INDEX `inst-id_idx` (`Inst_id` ASC) VISIBLE,
  CONSTRAINT `rid`
    FOREIGN KEY (`RID`)
    REFERENCES `Research DB`.`Researcher` (`RID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inst-id`
    FOREIGN KEY (`Inst_id`)
    REFERENCES `Research DB`.`Institute` (`InstID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Sponsoring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Sponsoring` (
  `ACT-ID` INT NOT NULL,
  `InstID` INT NOT NULL,
  PRIMARY KEY (`ACT-ID`, `InstID`),
  INDEX `InstID_idx` (`InstID` ASC) VISIBLE,
  CONSTRAINT `ACT-ID`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InstID`
    FOREIGN KEY (`InstID`)
    REFERENCES `Research DB`.`Institute` (`InstID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Agreement` (
  `RID` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  `End_Date` DATE NULL,
  `Start_Date` DATE NULL,
  `Total_Salary` VARCHAR(45) NULL,
  PRIMARY KEY (`RID`, `ACT-ID`),
  INDEX `ra key_idx` (`ACT-ID` ASC) VISIBLE,
  CONSTRAINT `ra key`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rs key`
    FOREIGN KEY (`RID`)
    REFERENCES `Research DB`.`Researcher` (`RID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Has_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Has_staff` (
  `Staff_id` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  PRIMARY KEY (`Staff_id`, `ACT-ID`),
  INDEX `actid_idx` (`ACT-ID` ASC) VISIBLE,
  CONSTRAINT `actid`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `staffid`
    FOREIGN KEY (`Staff_id`)
    REFERENCES `Research DB`.`Staff` (`Staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Topic` (
  `TopicID` INT NOT NULL,
  `Field` VARCHAR(45) NULL,
  `Topic` VARCHAR(45) NULL,
  PRIMARY KEY (`TopicID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Has_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Has_topic` (
  `TopicID` INT NOT NULL,
  `Act-ID` INT NOT NULL,
  PRIMARY KEY (`TopicID`, `Act-ID`),
  INDEX `Act-id_idx` (`Act-ID` ASC) VISIBLE,
  CONSTRAINT `Act-id`
    FOREIGN KEY (`Act-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `topicId`
    FOREIGN KEY (`TopicID`)
    REFERENCES `Research DB`.`Topic` (`TopicID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Finances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Finances` (
  `TRid` INT NOT NULL,
  `InstID` INT NULL,
  `Transaction type` VARCHAR(45) NULL,
  `Amount` INT NULL,
  PRIMARY KEY (`TRid`),
  INDEX `inst_num_idx` (`InstID` ASC) VISIBLE,
  CONSTRAINT `inst_num`
    FOREIGN KEY (`InstID`)
    REFERENCES `Research DB`.`Institute` (`InstID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `Research DB`.`Conducted_by`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Conducted_by` (
  `InstID` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  PRIMARY KEY (`InstID`, `ACT-ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Duty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Duty` (
  `RID` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  `Duty-ID` INT NOT NULL,
  `discription` VARCHAR(45) NULL,
  PRIMARY KEY (`RID`, `ACT-ID`, `Duty-ID`),
  CONSTRAINT `ag id`
    FOREIGN KEY (`RID` , `ACT-ID`)
    REFERENCES `Research DB`.`Agreement` (`RID` , `ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Transaction` (
  `NUM` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  `RID` INT NOT NULL,
  `item_id` VARCHAR(45) NULL,
  `Amount` VARCHAR(45) NULL,
  PRIMARY KEY (`NUM`, `ACT-ID`, `RID`),
  INDEX `ra_idx` (`ACT-ID` ASC) VISIBLE,
  CONSTRAINT `ra`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rs`
    FOREIGN KEY (`RID`)
    REFERENCES `Research DB`.`Researcher` (`RID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
