-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 21:18:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Research DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Research DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Research DB` DEFAULT CHARACTER SET utf8 ;
USE `Research DB` ;

-- -----------------------------------------------------
-- Table `Research DB`.`Researcher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Researcher` (
  `RID` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `Fav_field` VARCHAR(45) NULL,
  PRIMARY KEY (`RID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Research Activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Research Activity` (
  `ACT-ID` INT NOT NULL,
  `No_of_Pages` VARCHAR(45) NULL,
  `Start_Date` DATE NULL,
  `End_Date` DATE NULL,
  `INTL?` TINYINT NULL COMMENT '0 for domsetic and 1 for intl',
  `Date_Recieved` INT NULL,
  `Date_of_Admission` INT NULL,
  `TYPE` VARCHAR(45) NULL COMMENT 'Generalization \n',
  `TYPE_DATE` DATE NULL,
  `TYPE_PLACE` VARCHAR(45) NULL,
  `Correspondent` INT NOT NULL,
  PRIMARY KEY (`ACT-ID`),
  INDEX `Correspondent_idx` (`Correspondent` ASC) VISIBLE,
  UNIQUE INDEX `Correspondent_UNIQUE` (`Correspondent` ASC) VISIBLE,
  CONSTRAINT `FK_Correspondent_Researcher`
    FOREIGN KEY (`Correspondent`)
    REFERENCES `Research DB`.`Researcher` (`RID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Institute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Institute` (
  `InstID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `BoolRC` TINYINT NULL,
  `BoolEXE` TINYINT NULL,
  `boolGOV?` TINYINT NULL,
  `BoolUNI` TINYINT NULL,
  PRIMARY KEY (`InstID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Funding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Funding` (
  `InstID` INT NOT NULL,
  `ACT-ID` INT NOT NULL,
  `Loan_value` INT NULL,
  `Donation_value` INT NULL,
  PRIMARY KEY (`ACT-ID`, `InstID`),
  INDEX `InstID_idx` (`InstID` ASC) VISIBLE,
  CONSTRAINT `FK_Funding_Institute`
    FOREIGN KEY (`InstID`)
    REFERENCES `Research DB`.`Institute` (`InstID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Funding_Research_Activity`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Staff` (
  `Staff_id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Role` VARCHAR(45) NULL,
  `RA_or_inst_num` INT NOT NULL,
  PRIMARY KEY (`Staff_id`),
  INDEX `RA_or_inst_num_idx` (`RA_or_inst_num` ASC) VISIBLE,
  CONSTRAINT `FK_Staff_Research_Activity`
    FOREIGN KEY (`RA_or_inst_num`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Has_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Has_topic` (
  `ACT-ID` INT NOT NULL,
  `TopicID` INT NOT NULL,
  PRIMARY KEY (`TopicID`),
  INDEX `ACT-ID_idx` (`ACT-ID` ASC) VISIBLE,
  CONSTRAINT `FK_Has_topic_Research_Activity`
    FOREIGN KEY (`ACT-ID`)
    REFERENCES `Research DB`.`Research Activity` (`ACT-ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_Has_topic_Topic`
    FOREIGN KEY (`TopicID`)
    REFERENCES `Research DB`.`Topic` (`TopicID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research DB`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research DB`.`Topic` (
  `TopicID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`TopicID`)
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
